### ISSUE TITLE
Emit concatenated, re-named .fastq files into subdirectory within the nf-flu results directory

### ISSUE THREAD

**Issue by Codes1985** [CFIA-NCFAD/nf-flu#43]
Hello,

I was wondering about the feasibility of emitting the concatenated, re-named .fastq files into a subdirectory (e.g., fastq_files) within the nf-flu results directory.  This would facilitate downstream processes such as uploading to various repositories (e.g., IRIDA).

Thank you for your consideration.

**Comment by peterk87** [comment]
Fixed in #41 and released in [3.3.3](https://github.com/CFIA-NCFAD/nf-flu/releases/tag/3.3.3)
