### ISSUE TITLE
[BUG]: Mixed IAV and IBV run analysis reports all samples as IBV only

### ISSUE THREAD

**Issue by ayooluwaB** [CFIA-NCFAD/nf-flu#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the Bug/Issue

Pipeline unable to resolve mixed fluA and fluB run. I performed an analysis were the majority of the samples for the run were fluB confirmed and a handful were fluA confirmed. The subtyping report returned all samples as fluB. 

### Nextflow command-line

```shell
nextflow run CFIA-NCFAD/nf-flu -profile singularity,slurm --platform nanopore --input samplesheet_test.csv -r 3.3.2
```

### Error Message

```shell
Subtyping report file gives subtype for all samples as fluB even when fluA samples are present.
```

### Workflow Version

v3.3.2 and v3.3.3

### Nextflow Executor

slurm

### Nextflow Version

22.04.3

### Hardware

cluster

### Conda/Container Engine

Singularity

**Comment by peterk87** [comment]
Hi @ayooluwaB, would you be able to share the results privately?  I'm very interested in what's going on as I've tested the pipeline with both IAV and IBV samples and it has worked as expected. Have you looked at the IRMA results and reports? I'm not sure what could be going on.

**Comment by peterk87** [comment]
Hi @ayooluwaB just confirming that dehosting with a Kraken2 human seq index resolved your issue. I've added a TODO to add optional Kraken2 dehosting to the pipeline (#50).

**Comment by ayooluwaB** [comment]
Hi @peterk87, this is correct. I believe an optional dehosting step would be very beneficial.

**Comment by peterk87** [comment]
Great! I'll close this issue and leave #50 to tackle in a future PR.
