### ISSUE TITLE
Compatibility with cloud storage paths

### ISSUE THREAD

**Issue by ric-costa** [CFIA-NCFAD/nf-flu#55]
### Problem description

Hi! 

I noticed that the check_sample_sheet.py is not offering compatibility with cloud storage paths for the samples (such as az:// for azure or s3:// for AWS buckets). We simply changed line 30:
`if p.startswith("http") or p.startswith("ftp"):`

to:
`if p.startswith("http") or p.startswith("ftp") or p.startswith("az://") or p.startswith("s3://") or p.startswith("gs://"):`

and it seems to access the samples successfully.
Thank you!

**Comment by peterk87** [comment]
Thanks @ric-costa for reporting this issue! It should be fixed in [3.3.6](https://github.com/CFIA-NCFAD/nf-flu/releases/tag/3.3.6)

**Comment by ric-costa** [comment]
Thank you, @peterk87 , great pipeline!
